#!/usr/bin/env python3
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
"""Deterministic GitHub Actions workflow generator for the AGT monorepo.

The source of truth is ``.github/ci/workflows.toml`` plus the pinned action
registry ``.github/ci/actions.toml``. This script renders the committed YAML
under ``.github/workflows`` so CI configuration has a single reviewed manifest
instead of many hand edited files.

Usage::

    python3 scripts/ci/generate_workflows.py --write          # regenerate YAML
    python3 scripts/ci/generate_workflows.py --check          # fail on drift
    python3 scripts/ci/generate_workflows.py --sync-registry  # adopt bumped pins

``--sync-registry`` runs generation in reverse. Dependabot can edit a pinned
action in the generated workflow (which lives under ``.github/workflows``) but
cannot edit ``.github/ci/actions.toml`` (its source of truth), so such a bump
leaves the generated file drifting from the registry and ``--check`` fails. This
mode reads the bumped pin back out of the managed files, updates the registry to
match, and then regenerates exactly as ``--write`` does, which also rewrites the
generated workflow YAML and synchronizes the composite action pins under
``.github/actions`` to the registry. It is the deterministic equivalent of the
manual registry sync a maintainer would otherwise push on every actions bump.
Every path it reads or writes is validated to stay within the repository.

The renderer is intentionally deterministic and dependency free. It emits a
``DO NOT EDIT`` banner, enforces full SHA pinned actions resolved from the
registry, and restricts workflow level permissions to ``contents: read``. An
optional proposal agent may edit the manifest, but it never writes YAML and the
deterministic ``--check`` job is the gate, so generation stays reproducible and
reviewable.

The hand-authored composite actions under ``.github/actions`` are also checked
against the same action registry, and ``--write`` synchronizes their pins.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tomllib
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = REPO_ROOT / ".github" / "ci" / "workflows.toml"
ACTIONS_PATH = REPO_ROOT / ".github" / "ci" / "actions.toml"
COMPOSITE_ACTIONS_DIR = REPO_ROOT / ".github" / "actions"
COMPOSITE_ACTION_USES_RE = re.compile(
    r"^(?P<prefix>[ \t]*(?:-[ \t]+)?uses:[ \t]*)"
    r"(?P<value>[^\r\n]*?)(?P<newline>\r?\n)?$"
)

OPA_VERSION = "0.70.0"
OPA_LINUX_AMD64_SHA256 = "00d114b94fdb1606a48cccdfc73c9ccdc62c38721150131ae578d5ff3df5c084"
SHA_RE = re.compile(r"^[^@]+@[0-9a-f]{40}$")
KNOWN_TOOLCHAINS = {"rust", "python", "node", "dotnet"}

# Default toolchain versions. Kept here, not in the manifest, so the manifest
# stays terse and version bumps are a single reviewed edit.
PYTHON_VERSION = "3.12"
NODE_VERSION = "20"
DOTNET_VERSION = "8.0.x"

BANNER = (
    "# DO NOT EDIT. Generated by scripts/ci/generate_workflows.py.\n"
    "# Source: .github/ci/workflows.toml and .github/ci/actions.toml.\n"
    "# Regenerate: python3 scripts/ci/generate_workflows.py --write\n"
    "# Check drift: python3 scripts/ci/generate_workflows.py --check\n"
)


class GenerationError(Exception):
    """Raised when the manifest or registry is invalid."""


def _load_toml(path: Path) -> dict:
    try:
        with path.open("rb") as handle:
            return tomllib.load(handle)
    except FileNotFoundError as exc:
        raise GenerationError(f"missing required file: {path}") from exc
    except tomllib.TOMLDecodeError as exc:
        raise GenerationError(f"invalid TOML in {path}: {exc}") from exc


def _load_actions(path: Path) -> dict[str, str]:
    """Return a map of action key to a `uses` string with an inline comment."""
    raw = _load_toml(path)
    registry: dict[str, str] = {}
    for key, entry in raw.items():
        if not isinstance(entry, dict) or "uses" not in entry:
            raise GenerationError(f"action '{key}' must define a uses value")
        uses = entry["uses"]
        if not SHA_RE.match(uses):
            raise GenerationError(
                f"action '{key}' is not pinned to a 40 character SHA: {uses}"
            )
        comment = entry.get("comment")
        registry[key] = f"{uses} # {comment}" if comment else uses
    return registry


def _registry_by_action_name(actions: dict[str, str]) -> dict[str, str]:
    registry: dict[str, str] = {}
    for value in actions.values():
        reference = value.split(" #", 1)[0]
        action_name, separator, _revision = reference.partition("@")
        if not separator:
            raise GenerationError(
                f"registry entry is not pinned to a revision: {value}"
            )
        previous = registry.get(action_name)
        if previous is not None and previous != value:
            raise GenerationError(
                f"conflicting registry pins for action '{action_name}'"
            )
        registry[action_name] = value
    return registry


def _composite_action_files() -> list[Path]:
    if not COMPOSITE_ACTIONS_DIR.is_dir():
        raise GenerationError(
            f"missing composite actions directory: {COMPOSITE_ACTIONS_DIR}"
        )
    if COMPOSITE_ACTIONS_DIR.is_symlink():
        raise GenerationError(
            f"refusing to follow a symlinked composite actions directory: "
            f"{_display_path(COMPOSITE_ACTIONS_DIR)}"
        )
    boundary = COMPOSITE_ACTIONS_DIR.resolve()
    paths = {
        path
        for pattern in ("*/action.yml", "*/action.yaml")
        for path in COMPOSITE_ACTIONS_DIR.glob(pattern)
    }
    result: list[Path] = []
    for path in sorted(paths):
        # Containment: refuse any symlinked action file, and any path that
        # resolves outside the composite actions directory, so neither the pin
        # reader nor the writer can be made to follow a link out of the tree.
        if path.is_symlink():
            raise GenerationError(
                f"refusing to follow a symlinked composite action file: {path}"
            )
        if not path.resolve().is_relative_to(boundary):
            raise GenerationError(
                f"composite action path escapes "
                f"{_display_path(COMPOSITE_ACTIONS_DIR)}: {path}"
            )
        result.append(path)
    return result


def _display_path(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def _read_composite_action_lines(path: Path) -> list[str]:
    try:
        with path.open("r", encoding="utf-8", newline="") as handle:
            return handle.read().splitlines(keepends=True)
    except (OSError, UnicodeError) as exc:
        raise GenerationError(
            f"cannot read composite action file {_display_path(path)}: {exc}"
        ) from exc


def _inspect_composite_action_pins(
    actions: dict[str, str],
) -> tuple[list[str], list[str], dict[Path, str]]:
    registry_by_name = _registry_by_action_name(actions)
    drifted: list[str] = []
    invalid: list[str] = []
    rewrites: dict[Path, str] = {}

    for path in _composite_action_files():
        rel = _display_path(path)
        lines = _read_composite_action_lines(path)
        updated_lines: list[str] = []
        changed = False
        for line in lines:
            match = COMPOSITE_ACTION_USES_RE.match(line)
            if not match:
                updated_lines.append(line)
                continue

            value = match.group("value").strip()
            reference = value.split(maxsplit=1)[0] if value else ""
            if not reference:
                invalid.append(f"{rel}: uses step has no action reference")
                updated_lines.append(line)
                continue
            if reference.startswith(("./", "../", "docker://")):
                updated_lines.append(line)
                continue

            action_name = reference.split("@", 1)[0]
            canonical = registry_by_name.get(action_name)
            if canonical is None:
                invalid.append(
                    f"{rel}: '{reference}' is not registered in .github/ci/actions.toml"
                )
                updated_lines.append(line)
                continue

            if value != canonical:
                drifted.append(
                    f"{rel}: '{reference}' does not match registry pin '{canonical}'"
                )
                updated_lines.append(
                    f"{match.group('prefix')}{canonical}{match.group('newline') or ''}"
                )
                changed = True
            else:
                updated_lines.append(line)

        if changed:
            rewrites[path] = "".join(updated_lines)

    return drifted, invalid, rewrites


def check_composite_action_pins(actions: dict[str, str]) -> list[str]:
    """Return drift and unregistered remote action references in local actions."""
    drifted, invalid, _rewrites = _inspect_composite_action_pins(actions)
    return invalid + drifted


def sync_composite_action_pins(actions: dict[str, str]) -> list[Path]:
    """Rewrite registered composite action references to match the registry."""
    _drifted, invalid, rewrites = _inspect_composite_action_pins(actions)
    if invalid:
        raise GenerationError("\n".join(invalid))

    changed: list[Path] = []
    for path, content in rewrites.items():
        try:
            with path.open("w", encoding="utf-8", newline="") as handle:
                handle.write(content)
        except (OSError, UnicodeError) as exc:
            raise GenerationError(
                f"cannot write composite action file {_display_path(path)}: {exc}"
            ) from exc
        changed.append(path)
    return changed


# Anchored to a real step line: optional indent, an optional "- " list dash, then
# "uses:". A commented-out line ("# - uses: ...@sha # v9.0.0") starts with "#"
# after the indent and therefore never matches, so it is not treated as a pin
# source. Use with .match (start-anchored).
_PIN_LINE_RE = re.compile(
    r"\s*(?:-\s+)?uses:\s*(?P<ref>[A-Za-z0-9._/-]+@[0-9a-f]{40})(?:\s*#\s*(?P<comment>.+?))?\s*$"
)
_SECTION_RE = re.compile(r"^\[(?P<key>[^\]]+)\]\s*$")
# A trailing comment that looks like a resolvable version tag (e.g. "v7.0.1").
# Non-version comments such as "stable" are not resolvable to a single commit and
# are left unverified.
_VERSION_COMMENT_RE = re.compile(r"^v\d+(?:\.\d+)*$")
# Version comments adopted into the registry are written as a TOML string, so
# constrain them to the shape of a real tag ("v7.0.1", "stable") and refuse
# anything that could break out of the quotes rather than embedding it.
_SAFE_COMMENT_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9 ._+:/-]*$")


def _registry_key_by_action_name(actions: dict[str, str]) -> dict[str, str]:
    """Map a bare action name (owner/repo) to its registry key."""
    mapping: dict[str, str] = {}
    for key, value in actions.items():
        reference = value.split(" #", 1)[0]
        action_name = reference.split("@", 1)[0]
        mapping[action_name] = key
    return mapping


def _managed_pin_sources() -> list[Path]:
    """Files whose action pins must track the registry.

    These are the generated workflow outputs plus the hand-authored composite
    actions. Every registry entry is, by the registry's own contract, referenced
    by at least one of these, so a Dependabot bump of any registered action lands
    in one of them.
    """
    sources = list(build_outputs().keys())
    sources.extend(_composite_action_files())
    return sources


def collect_registry_updates(
    actions: dict[str, str],
) -> dict[str, tuple[str, str | None]]:
    """Return registry updates implied by pins in the managed files.

    Scans the generated workflows and composite actions for pinned references
    whose action name is in the registry, and reports any that differ from the
    registry. This is the reverse of generation: it reads a Dependabot bump back
    out of a file Dependabot can edit so the registry can adopt it.

    Returns a map of registry key to (new_uses, new_comment). Raises
    GenerationError if two managed files disagree on the pin for the same action.
    """
    key_by_name = _registry_key_by_action_name(actions)
    observed: dict[str, tuple[str, str | None, str]] = {}

    for path in _managed_pin_sources():
        if not path.exists():
            continue
        rel = _display_path(path)
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as exc:
            raise GenerationError(f"cannot read {rel}: {exc}") from exc
        for line in text.splitlines():
            match = _PIN_LINE_RE.match(line)
            if not match:
                continue
            ref = match.group("ref")
            key = key_by_name.get(ref.split("@", 1)[0])
            if key is None:
                continue
            comment = match.group("comment")
            comment = comment.strip() if comment else None
            if comment is not None and not _SAFE_COMMENT_RE.match(comment):
                raise GenerationError(
                    f"refusing to adopt unsafe version comment for "
                    f"'{ref.split('@', 1)[0]}' from {rel}: {comment!r}"
                )
            prior = observed.get(key)
            if prior is not None and (prior[0], prior[1]) != (ref, comment):
                raise GenerationError(
                    f"conflicting pins for '{ref.split('@', 1)[0]}': "
                    f"{prior[2]} has '{prior[0]}' but {rel} has '{ref}'"
                )
            observed[key] = (ref, comment, rel)

    updates: dict[str, tuple[str, str | None]] = {}
    for key, (ref, comment, _rel) in observed.items():
        current = actions[key]
        current_uses = current.split(" #", 1)[0]
        current_comment = (
            current.split(" #", 1)[1].strip() if " #" in current else None
        )
        if (ref, comment) != (current_uses, current_comment):
            updates[key] = (ref, comment)
    return updates


def _rewrite_actions_toml(updates: dict[str, tuple[str, str | None]]) -> None:
    """Rewrite the uses/comment of the named registry entries in place.

    Operates line by line so the registry file keeps its layout and comments.
    """
    if ACTIONS_PATH.is_symlink():
        raise GenerationError(
            f"refusing to write through a symlinked registry path: "
            f"{_display_path(ACTIONS_PATH)}"
        )
    try:
        lines = ACTIONS_PATH.read_text(encoding="utf-8").splitlines(keepends=True)
    except (OSError, UnicodeError) as exc:
        raise GenerationError(f"cannot read {_display_path(ACTIONS_PATH)}: {exc}") from exc

    current_key: str | None = None
    out: list[str] = []
    for line in lines:
        section = _SECTION_RE.match(line)
        if section:
            current_key = section.group("key")
            out.append(line)
            continue
        if current_key in updates:
            uses, comment = updates[current_key]
            stripped = line.lstrip()
            indent = line[: len(line) - len(stripped)]
            newline = "\n" if line.endswith("\n") else ""
            if stripped.startswith("uses ="):
                out.append(f'{indent}uses = "{uses}"{newline}')
                continue
            if stripped.startswith("comment ="):
                if comment is None:
                    continue
                out.append(f'{indent}comment = "{comment}"{newline}')
                continue
        out.append(line)

    try:
        ACTIONS_PATH.write_text("".join(out), encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        raise GenerationError(
            f"cannot write {_display_path(ACTIONS_PATH)}: {exc}"
        ) from exc


def _resolve_tag_commit_sha(action_name: str, version: str, *, token: str | None) -> str | None:
    """Resolve ``owner/repo@version`` to the 40-hex commit SHA that tag points to,
    via the GitHub API. Returns the lowercased SHA, or None if it cannot be
    resolved (network/auth error, missing tag, malformed response).
    """
    url = f"https://api.github.com/repos/{action_name}/commits/{version}"
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "agt-generate-workflows",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
    req = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:  # fixed https GitHub host
            payload = json.load(resp)
    except Exception:
        return None
    sha = str(payload.get("sha", "")).lower()
    return sha if re.fullmatch(r"[0-9a-f]{40}", sha) else None


def verify_pin_versions(
    updates: dict[str, tuple[str, str | None]], *, token: str | None
) -> None:
    """Confirm each adopted pin's SHA is the commit its version comment resolves to.

    Fails closed: a version-tagged pin whose SHA does not match, or cannot be
    resolved, is refused, so a bumped SHA that does not correspond to its ``# vX``
    comment is never written into the registry. Non-version comments (for example
    "stable") are not resolvable to a single commit and are left unverified.
    """
    for _key, (uses, comment) in sorted(updates.items()):
        if not comment or not _VERSION_COMMENT_RE.match(comment):
            continue
        action_name, _sep, sha = uses.partition("@")
        sha = sha.lower()
        resolved = _resolve_tag_commit_sha(action_name, comment, token=token)
        if resolved is None:
            raise GenerationError(
                f"cannot verify {action_name}@{comment} resolves to a commit "
                f"(network/token/tag); refusing to adopt {sha}"
            )
        if resolved != sha:
            raise GenerationError(
                f"pin mismatch for {action_name}: {comment} resolves to "
                f"{resolved}, not {sha}"
            )


def sync_registry_from_tree(*, verify: bool = True) -> list[str]:
    """Adopt pins bumped in managed files into the registry.

    When ``verify`` is true (the default), each adopted version-tagged pin is
    checked against the GitHub API so a SHA that does not resolve to its ``# vX``
    comment is refused rather than written in. Returns the sorted registry keys
    that were updated.
    """
    if ACTIONS_PATH.is_symlink():
        raise GenerationError(
            f"refusing to read or write a symlinked registry path: "
            f"{_display_path(ACTIONS_PATH)}"
        )
    actions = _load_actions(ACTIONS_PATH)
    updates = collect_registry_updates(actions)
    if updates and verify:
        token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
        verify_pin_versions(updates, token=token)
    if updates:
        _rewrite_actions_toml(updates)
    return sorted(updates)


def _indent(text: str, spaces: int) -> list[str]:
    pad = " " * spaces
    return [f"{pad}{line}" if line else "" for line in text.splitlines()]


def _render_uses_step(action_ref: str, name: str | None, with_lines: list[str]) -> list[str]:
    lines: list[str] = []
    if name:
        lines.append(f"      - name: {name}")
        lines.append(f"        uses: {action_ref}")
    else:
        lines.append(f"      - uses: {action_ref}")
    if with_lines:
        lines.append("        with:")
        lines.extend(f"          {line}" for line in with_lines)
    return lines


def _render_run_step(name: str, run_body: str) -> list[str]:
    lines = [f"      - name: {name}", "        run: |"]
    body = run_body.strip("\n")
    for line in body.splitlines():
        lines.append(f"          {line}" if line else "")
    return lines


def _toolchain_steps(toolchain: str, actions: dict[str, str]) -> list[str]:
    if toolchain == "rust":
        return _render_uses_step(
            actions["rust-toolchain"],
            "Install Rust toolchain",
            ["toolchain: stable", "components: rustfmt, clippy"],
        )
    if toolchain == "python":
        return _render_uses_step(
            actions["setup-python"],
            "Set up Python",
            [f"python-version: '{PYTHON_VERSION}'"],
        )
    if toolchain == "node":
        return _render_uses_step(
            actions["setup-node"],
            "Set up Node.js",
            [f"node-version: '{NODE_VERSION}'"],
        )
    if toolchain == "dotnet":
        return _render_uses_step(
            actions["setup-dotnet"],
            "Set up .NET",
            [f"dotnet-version: '{DOTNET_VERSION}'"],
        )
    raise GenerationError(f"unknown toolchain: {toolchain}")


def _opa_step(on_path: bool = False, set_env: bool = True) -> list[str]:
    lines = [
        f'curl --proto \'=https\' --tlsv1.2 -fSLo "$RUNNER_TEMP/opa" '
        '--retry 5 --retry-all-errors --retry-delay 5 --connect-timeout 20 '
        f'"https://openpolicyagent.org/downloads/v{OPA_VERSION}/opa_linux_amd64_static"\n',
        f'echo "{OPA_LINUX_AMD64_SHA256}  $RUNNER_TEMP/opa" | sha256sum -c -\n',
        'chmod +x "$RUNNER_TEMP/opa"\n',
    ]
    if set_env:
        lines.append('echo "ACS_OPA_PATH=$RUNNER_TEMP/opa" >> "$GITHUB_ENV"\n')
    if on_path:
        # The Python generator locates opa via shutil.which("opa") (PATH only),
        # unlike the Rust core which honors ACS_OPA_PATH. Jobs that run the
        # generator opt in to also putting opa on PATH.
        lines.append('echo "$RUNNER_TEMP" >> "$GITHUB_PATH"\n')
    lines.append('"$RUNNER_TEMP/opa" version')
    return _render_run_step("Install OPA", "".join(lines))


def _render_job(job: dict, actions: dict[str, str]) -> list[str]:
    job_id = job.get("id")
    if not job_id:
        raise GenerationError("every job needs an id")
    name = job.get("name", job_id)
    toolchains = job.get("toolchains", [])
    unknown = set(toolchains) - KNOWN_TOOLCHAINS
    if unknown:
        raise GenerationError(f"job '{job_id}' uses unknown toolchains: {sorted(unknown)}")
    steps = job.get("step", [])
    if not steps:
        raise GenerationError(f"job '{job_id}' has no steps")

    lines = [f"  {job_id}:", f"    name: {name}", "    runs-on: ubuntu-latest", "    timeout-minutes: 30"]
    working_directory = job.get("working_directory")
    if working_directory:
        lines += ["    defaults:", "      run:", f"        working-directory: {working_directory}"]
    lines.append("    steps:")
    lines += _render_uses_step(actions["checkout"], None, [])
    for toolchain in toolchains:
        lines += _toolchain_steps(toolchain, actions)
    if job.get("opa"):
        lines += _opa_step(job.get("opa_on_path", False), job.get("opa_env", True))
    for step in steps:
        step_name = step.get("name")
        run_body = step.get("run")
        if not step_name or run_body is None:
            raise GenerationError(f"job '{job_id}' has a step missing name or run")
        lines += _render_run_step(step_name, run_body)
    return lines


def render_workflow(workflow: dict, actions: dict[str, str]) -> str:
    name = workflow.get("name")
    if not name:
        raise GenerationError("every workflow needs a name")
    output = workflow.get("output", "")
    if not output.startswith(".github/workflows/") or not output.endswith(".yml"):
        raise GenerationError(f"workflow '{name}' output must be a .github/workflows/*.yml path")

    push_branches = workflow.get("push_branches", [])
    pull_request_paths = workflow.get("pull_request_paths", [])

    lines = [BANNER.rstrip("\n"), f"name: {name}", "", "on:"]
    if push_branches:
        lines.append("  push:")
        lines.append("    branches:")
        lines += [f"      - {branch}" for branch in push_branches]
    if pull_request_paths:
        lines.append("  pull_request:")
        lines.append("    paths:")
        lines += [f"      - '{path}'" for path in pull_request_paths]
    lines += [
        "",
        "permissions:",
        "  contents: read",
        "",
        "concurrency:",
        "  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}",
        "  cancel-in-progress: true",
        "",
        "jobs:",
    ]
    jobs = workflow.get("job", [])
    if not jobs:
        raise GenerationError(f"workflow '{name}' has no jobs")
    for index, job in enumerate(jobs):
        if index:
            lines.append("")
        lines += _render_job(job, actions)
    return "\n".join(lines) + "\n"


def build_outputs(actions: dict[str, str] | None = None) -> dict[Path, str]:
    if actions is None:
        actions = _load_actions(ACTIONS_PATH)
    manifest = _load_toml(MANIFEST_PATH)
    workflows = manifest.get("workflow", [])
    if not workflows:
        raise GenerationError("manifest defines no [[workflow]] entries")
    outputs: dict[Path, str] = {}
    seen_ids: set[str] = set()
    repo_root = REPO_ROOT.resolve()
    for workflow in workflows:
        wid = workflow.get("id", "")
        if wid in seen_ids:
            raise GenerationError(f"duplicate workflow id: {wid}")
        seen_ids.add(wid)
        content = render_workflow(workflow, actions)
        out_path = REPO_ROOT / workflow["output"]
        # Containment: the manifest output must resolve beneath the repo, so a
        # traversal like .github/workflows/../../../x.yml cannot make the
        # generator (or --sync-registry, which reads these paths) touch a file
        # outside the tree.
        if not out_path.resolve().is_relative_to(repo_root):
            raise GenerationError(
                f"workflow '{workflow.get('name', wid)}' output escapes the "
                f"repository: {workflow['output']}"
            )
        outputs[out_path] = content
    return outputs


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="write generated workflow YAML")
    group.add_argument("--check", action="store_true", help="fail if committed YAML drifts")
    group.add_argument(
        "--sync-registry",
        action="store_true",
        help="adopt action pins bumped in the generated workflows or composite "
        "actions into actions.toml, then regenerate",
    )
    parser.add_argument(
        "--no-verify-pins",
        action="store_true",
        help="with --sync-registry, skip the GitHub API check that each adopted "
        "SHA resolves to its version comment (offline/emergency use only)",
    )
    args = parser.parse_args(argv)

    if args.sync_registry:
        try:
            updated = sync_registry_from_tree(verify=not args.no_verify_pins)
        except GenerationError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 2
        for key in updated:
            print(f"synced registry entry: {key}")
        if not updated:
            print("registry already matches the pins in the managed files")

    try:
        actions = _load_actions(ACTIONS_PATH)
        outputs = build_outputs(actions)
    except GenerationError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    if args.write or args.sync_registry:
        try:
            synced = sync_composite_action_pins(actions)
        except GenerationError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 2
        for path, content in outputs.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            with path.open("w", encoding="utf-8", newline="\n") as handle:
                handle.write(content)
            print(f"wrote {path.relative_to(REPO_ROOT)}")
        for path in synced:
            print(f"synced {_display_path(path)}")
        return 0

    drifted: list[str] = []
    for path, content in outputs.items():
        rel = path.relative_to(REPO_ROOT)
        if not path.exists():
            drifted.append(f"{rel} (missing, run --write)")
        elif path.read_text(encoding="utf-8") != content:
            drifted.append(f"{rel} (out of date, run --write)")
    try:
        drifted.extend(check_composite_action_pins(actions))
    except GenerationError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    if drifted:
        print(
            "error: generated workflows or composite action pins are out of date:",
            file=sys.stderr,
        )
        for item in drifted:
            print(f"  - {item}", file=sys.stderr)
        return 1
    print("generated workflows and composite action pins are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
