// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Security.Cryptography;

namespace AgentGovernance.Trust;

/// <summary>
/// Provides peer verification capabilities using challenge-response protocols.
/// Verifies that a peer possesses the signing key corresponding to its claimed identity
/// using caller-supplied proof material.
/// </summary>
public static class TrustVerifier
{
    /// <summary>
    /// Legacy overload retained for source and binary compatibility.
    /// </summary>
    /// <remarks>
    /// Self-attesting verification is no longer supported. Callers must supply proof
    /// generated by the peer via <see cref="VerifyPeer(string, AgentIdentity, byte[], byte[])"/>.
    /// </remarks>
    [Obsolete(
        "Self-attesting peer verification is no longer supported. Use VerifyPeer(string, AgentIdentity, byte[], byte[]) with externally supplied challenge and signature proof.")]
    public static bool VerifyPeer(string peerId, AgentIdentity peerIdentity)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(peerId);
        ArgumentNullException.ThrowIfNull(peerIdentity);

        return false;
    }

    /// <summary>
    /// Verifies a peer's identity using caller-supplied challenge-response proof.
    /// </summary>
    /// <param name="peerId">The expected DID of the peer being verified.</param>
    /// <param name="peerIdentity">
    /// The <see cref="AgentIdentity"/> presented by the peer. Only asymmetric identities
    /// can be externally verified because compatibility identities require private key material.
    /// </param>
    /// <param name="challenge">The verifier-generated challenge bytes that were sent to the peer.</param>
    /// <param name="signature">The signature returned by the peer over <paramref name="challenge"/>.</param>
    /// <returns><c>true</c> if the peer's identity is verified; otherwise <c>false</c>.</returns>
    /// <exception cref="ArgumentException">
    /// Thrown when <paramref name="peerId"/> is null or whitespace.
    /// </exception>
    /// <exception cref="ArgumentNullException">
    /// Thrown when <paramref name="peerIdentity"/>, <paramref name="challenge"/>, or
    /// <paramref name="signature"/> is <c>null</c>.
    /// </exception>
    /// <remarks>
    /// This method never signs on behalf of the peer. Callers are responsible for generating
    /// a fresh cryptographically random challenge and obtaining the peer's signature out-of-band.
    /// </remarks>
    public static bool VerifyPeer(
        string peerId,
        AgentIdentity peerIdentity,
        byte[] challenge,
        byte[] signature)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(peerId);
        ArgumentNullException.ThrowIfNull(peerIdentity);
        ArgumentNullException.ThrowIfNull(challenge);
        ArgumentNullException.ThrowIfNull(signature);

        if (peerIdentity.Did != AgentIdentity.NormalizeDid(peerId))
        {
            return false;
        }

        if (challenge.Length == 0 || signature.Length == 0)
        {
            return false;
        }

        if (peerIdentity.SigningAlgorithm != IdentitySigningAlgorithm.EcdsaP256)
        {
            return false;
        }

        try
        {
            return AgentIdentity.VerifySignature(
                peerIdentity.PublicKey,
                challenge,
                signature,
                signingAlgorithm: peerIdentity.SigningAlgorithm);
        }
        catch (InvalidOperationException)
        {
            return false;
        }
        catch (CryptographicException)
        {
            return false;
        }
    }
}
