name: Spell Check

on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.md"
      - ".cspell.json"
      - ".cspell-repo-terms.txt"
      - ".github/workflows/spell-check.yml"

permissions:
  contents: read
  pull-requests: read

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Get changed markdown files
        id: changed-markdown
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            **/*.md

      - name: Install cspell
        run: npm install --ignore-scripts --global cspell@8.17.3

      - name: Check spelling
        if: steps.changed-markdown.outputs.any_changed == 'true'
        env:
          CHANGED_FILES: ${{ steps.changed-markdown.outputs.all_changed_files }}
        run: cspell --config .cspell.json --no-progress $CHANGED_FILES
