name: Spell Check

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  typos:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Check spelling with typos
        uses: crate-ci/typos@master
        with:
          files: "**/*.md"
